language: python
python: "2.7"
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/test
  - bin/flake8 src/experimental
after_success:
  - bin/createcoverage run --src=src/experimental bin/test -s experimenal.localrolesindex
  - pip install -q coveralls
  - coveralls
notifications:
  email: plone.intranet@netsight.co.uk
  irc: "chat.freenode.net#ploneintranet"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
